### PR TITLE
Reduce identify time by ~8 seconds

### PR DESCRIPTION
**Pull request by reqyl**
Previously the cain dialog would stay open blocking inventory key from working (when checking items), the bot would be in some loop for 8 seconds before closing it and continuing.

### CODE REVIEW

**Comment by derek337** [comment]
This works well, I tested locally. Much faster.

**Comment by mgleed** [comment]
This used to be on master but there are a few cases where it fails. I don't remember what they were now. Tried the return to play method but even that doesn't work for everyone so had to increase the time. Best is to use an ID tome til someone makes a permanent solution.

**Comment by derek337** [comment]
> This used to be on master but there are a few cases where it fails. I don't remember what they were now. Tried the return to play method but even that doesn't work for everyone so had to increase the time. Best is to use an ID tome til someone makes a permanent solution.

How does ID tomes work? Will the program just attempt to use it if present in character inventory?

**Comment by mgleed** [comment]
Yes

**Comment by reqyl** [comment]
I checked the git history for this file and it look to me that the code was last changed here #582

The previous behavior seems to have been that the dialog wasn't closed at all (maybe after some timeout somewhere though)

So I think this change is still relevant and correct. In the current code some loop inside `view.return_to_play()` is what is taking the extra 8 seconds.

**Comment by mgleed** [comment]
> Previously the cain dialog would stay open blocking inventory key from working (when checking items),

Hey I'm trying to see if I can fix the original return_to_play() function. Could you capture this on video or with screenshots?

**Comment by mgleed** [comment]
I couldn't reproduce the issue, but I can tell where it was likely going wrong. The NPCMenu often disappears for a fraction of a second before reappearing after hitting the identify button which likely caused issues with the view.return_to_play() function. I added a couple small adjustments but this should work now.

**Review by mgleed — APPROVED** [review]

**Review by mgleed — CHANGES_REQUESTED** [review]
looks like your rebase / force push reverted some changes from master, gonna see if i can salvage the changes

**Comment by mgleed** [comment]
Had to open new PR #837

**Pull request closed without merging**
