### PR TITLE
Make log chicken an option

### PR DESCRIPTION
**Pull request by drallcom3**
It can produce a lot of spam for low level bots.

### CODE REVIEW

**Comment by D2RLegit** [comment]
I feel like this is more of a personal want then something we need congesting up in default params.

**Comment by Aimware0** [comment]
Looks right to me

**Comment by D2RLegit** [comment]
I would say no to this pr. Imo we don't need this in default botty. Chickens are seldom to none for the most part (outisde of the first 2 days of reset) where discord sends chicken logs shouldn't be a big deal to most.

**Comment by bad-magick** [comment]
As a user I can say this would be very helpful. Since I run a few bots would be nice to be able to troubleshoot setups and have a better logs of what happens during gameplay. I experience chickens often. I’m sure there are other users that do too.

Bitty should be for both those with optimal and suboptimal setups. This would definitely be for those of us who don’t run perfect gear.

Just my thoughts. 😊

d

**Comment by D2RLegit** [comment]
It already logs for chickens but default. Not sure how it would be helpful to have the ability to turn it off.

**Comment by drallcom3** [comment]
I made it, because for bots with not so good items it produces a lot of messages. You might not actually care that your bots chickens 10% of the runs, but you don't lke that the chicken messages spam away the item found mesages.

This feature is not in any way super important though. Do with it whatver you see fit.

**Review by mgleed — APPROVED** [review]
Thank you for your work on this

**Pull request merged**
