### PR TITLE
support list input for template_finder.search()

### PR DESCRIPTION
**Pull request by mgleed**
Think this could be a helpful feature for future stuff I might work on, wanted to merge earlier than later. I wanted to also return the name of the template found, but not sure how to do that since `ref` can be an image, not just a string or list.

### CODE REVIEW

**Comment by aeon0** [comment]
Yeah, could be useful, you could return None in case ref is an image.
Right now it will return the first template that is higher then the threshold? Do we want that, or is it better to search for all refs and return the one with the highest score?

**Comment by mgleed** [comment]
Added an input parameter `best_match` for the search function, and added a third output with the template name. This is untested as I haven't come up with a test use case for it yet (I had something like this for rejuv vs. full rejuv potion in old belt manager), but I can try tomorrow. @aeon0

**Comment by mgleed** [comment]
Changed the output type from (bool, float) to an object containing name, position, and score. Looked for all the places in sourcecode that used template_finder search() and search_and_wait() and adjusted accordingly. Reworked the logic on a couple spots.

Runs well. Have run a few runs, resurrected merc, and a few other things without issue but have not comprehensively tested outside of that.

Demo of best_match on vs best_match off:
search_bestMatch_off
search_bestMatch_on
 
@aeon0 let me know what you think

**Comment by mgleed** [comment]
K should be done with it til review now. :p

**Comment by aeon0** [comment]
Could you maybe make this branch again on the base botty repo, not on your fork. Would make life much easier for me to test stuff.
while on your branch this should do it
```
git remote add mgleed your_git_repo
git fetch mgleed
git checkout mgleed/multiSearch
# now you on a detached head
git checkout -b multiSearch
git push -u origin multiSearch
```

**Pull request closed without merging**
