### PR TITLE
Updates act 2 template

### PR DESCRIPTION
**Pull request by D2RLegit**

### CODE REVIEW

**Review by mgleed — COMMENTED** [review]
what is the new template for? I don't see any pathing information included for it

**Comment by D2RLegit** [comment]
> 
its included in town check


> what is the new template for (# 27)? I don't see any pathing information included for it

Its only for wait at tp check. Another user added it and said it worked to prevent getting stuck at act 2 at tp ><

**Comment by mgleed** [comment]
> > 
> 
> its included in town check
> 
> > what is the new template for (# 27)? I don't see any pathing information included for it
> 
> Its only for wait at tp check. Another user added it and said it worked to prevent getting stuck at act 2 at tp ><

what version were they running when they were geting stuck? this was fixed in #713

**Comment by Wullff91** [comment]
Me getting stuck in act 2 town aswell using this for 1 week now

**Comment by D2RLegit** [comment]
> Me getting stuck in act 2 town aswell using this for 1 week now

literally made this pr 2 days ago.

**Comment by derek337** [comment]
[#713](https://github.com/aeon0/botty/pull/713) did not fix the template issues in A2 for me. I just pulled in @D2RLegit changes locally and testing now. 

Basically I'm seeing a 30% failure rate on Arcane runs with the current templates in mater. We will see if this resolves that.

**Comment by derek337** [comment]
This works well, I hope it gets merged.

**Review by mgleed — APPROVED** [review]
Thank you for this

**Pull request merged**
