### PR TITLE
Enhancement: Faster save and exit using keyboard

### PR DESCRIPTION
**Pull request by roozhou**
Faster save and exit using esc->up->enter. No wait on menu and mouse move.

### CODE REVIEW

**Comment by D2RLegit** [comment]
We tried this already and would cause issues at char screen.

**Comment by roozhou** [comment]
> We tried this already and would cause issues at char screen. When you would fail to chicken in time.

Isn't char screen only used in town?

**Comment by D2RLegit** [comment]
It would add an issue at the main screen where all your characters are. If you fail to chicken in time, it wants to try to exit out of d2r at the main screen.

**Comment by D2RLegit** [comment]
Ill stress test this sometime this week to see if that issue still persists.

**Comment by roozhou** [comment]
Tested locally for a week. Made some changes to improve reliability:
1) Keep pressing ESC until the game menu is visible (make sure char/inventory screen is closed)
2) Check the highlighted menu item (it remembers your last selection in the game)

Now it uses one template match to do both steps. Should improve chicken response time.

**Comment by D2RLegit** [comment]
> Tested locally for a week. Made some changes to improve reliability:
> 
>     1. Keep pressing ESC until the game menu is visible (make sure char/inventory screen is closed)
> 
>     2. Check the highlighted menu item (it remembers your last selection in the game)
> 
> 
> Now it uses one template match to do both steps. Should improve chicken response time.

I was going to mention that it could get stuck on death screen if it doesn't chicken in time, haven't had time to review anything since Ive been super busy. not sure if anyone else can stress test this with very low chicken rate in somewhere like trav with sorc to verify that it'll still function properly if it char dies before trying to chicken.

**Comment by roozhou** [comment]
> 

Do you mean it gets stuck when the char dies at the game menu?

**Comment by D2RLegit** [comment]
Stress tested this. No issues even if fails to chicken in time. Should be good to go.

**Review by mgleed — APPROVED** [review]
Looks good, thank you for your work on this and thank you @D2RLegit for testing.

**Pull request merged**
