### PR TITLE
Parallelize template searching

### PR DESCRIPTION
**Pull request by Ezro**
Proposal to parallelize search_and_wait template waiting using futures.

### CODE REVIEW

**Comment by VladimirMakaev** [comment]
Given the fact that this is CPU bound workload do you have any metrics behind this change? My concern is that we'll have spikes in CPU consumption by botty while it's already mostly run in a constrained environment with many VMs fighting for resources. I may be wrong so some metrics would be nice

**Comment by Ezro** [comment]
> 

I don't have any concrete benchmarks on hand, but when I developed this I noticed that the initial A5_... searching took >1s for multiple searches (until found). With the current implementation in main, this also will run into scalability issues if you ever wanted to match against larger sets.

From my testing, those calls were reduced from >1s to ~0.2s (if memory serves).

The PR includes debug lines for printing the elapsed time for image grabbing as well as searching; I'd encourage pulling down the branch and messing around with the before vs after.

**Comment by Ezro** [comment]
> I completely understand that you'd decrease the search latency as you'll utilize more CPU cores. My concern is about how it would affect setups with VMs and whether you won't overcommit your CPU or create more issues in constrained environments. Ideally the amount of threads you create should be capped somehow based on the amount of cores. I'm not sure if ThreadPoolExecutor would do it natively, let me know if it does
> 
> Also I don't think Futures is the right abstraction for the problem and I'd rather go for a solution with "Parallel-For" semantics that gives an ability to limit concurrency and has a much cleaner syntax with exactly the same outcome. That would allow to limit your concurrency to 1 by a setting a parameter in config as well
> 
> But I'd ask @aeon0 to review this anyway as those are just my thoughts

That's fair. I don't use a VM for my setup so I'm unable to test the solution against it.

From the [Python docs](https://docs.python.org/dev/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor):
`If max_workers is None or not given, it will default to the number of processors on the machine, multiplied by 5, assuming that [ThreadPoolExecutor](https://docs.python.org/dev/library/concurrent.futures.html#concurrent.futures.ThreadPoolExecutor) is often used to overlap I/O instead of CPU work and the number of workers should be higher than the number of workers for [ProcessPoolExecutor](https://docs.python.org/dev/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor).`

We could manually set the max_workers, but I'm not convinced that the default behavior would be detrimental to a VM.

re: Futures vs Parallel-For (multiprocessing?), I think this is more of a subjective thing; imo, futures should be the go-to for the majority of parallelized tasks since it has a simpler API and my understanding is that it was designed specifically as an easier-to-use replacement for existing concurrent libs (like multiprocessing).

**Comment by Ezro** [comment]
Main CPU Benchmark
Parallel Search CPU Benchmark

**Comment by VladimirMakaev** [comment]
It doesn't look bad based on the benchmark data. Thanks for getting this. Main folks who probably wouldn't like this are the ones running 3 VMs but if the bottleneck is GPU rather than CPU it can work out just fine.

**Comment by mgleed** [comment]
@Ezro if you're still interested in this PR, see if you can rebase/merge given recent template_finder changes. Will review again at that point. Thanks!

**Comment by jobithu** [comment]
Imagine what we could do with our mob detection if this thing here was working :)

**Comment by mgleed** [comment]
Closing for now, can revisit in the future if need arises

**Pull request closed without merging**
