### PR TITLE
Better pathing for walkers in trav

### PR DESCRIPTION
**Pull request by D2RLegit**
updated node with more assets. Node 225 notorious for for causing stutters. this fixes it.

### CODE REVIEW

**Review by xanep — APPROVED** [review]
This works really well. Tried 100+ runs and had no failures in travincal anymore

**Review by tjamesallen15 — APPROVED** [review]

**Comment by mgleed** [comment]
Any performance impact with this on your vm's? Adding an extra 10 assets for a single node seems like a lot of overhead.

**Comment by mgleed** [comment]
> > Any performance impact with this on your vm's? Adding an extra 10 assets to search for every teleport for a single node seems like a lot of overhead.
> 
> Heavily reduced chickens and fails for all walking chars

Yeah I understand what the PR is for. How does it impact performance on your VM with walking characters?

**Comment by D2RLegit** [comment]
> > > Any performance impact with this on your vm's? Adding an extra 10 assets to search for every teleport for a single node seems like a lot of overhead.
> > 
> > 
> > Heavily reduced chickens and fails for all walking chars
> 
> Yeah I understand what the PR is for. How does it impact performance on your VM with walking characters?

Works much better on VM. I was running for awhile without issues on my vm. Im sure you could cutback on assets but more work to reverse engineering the assets them I'm willing to put into it.

**Review by mgleed — APPROVED** [review]
Works as far as i can tell

**Pull request merged**
