### PR TITLE
Added small explanation to JavaShopper class.

### PR DESCRIPTION
**Pull request by bjoerm**

### CODE REVIEW

**Comment by karibuTW** [comment]
Thanks for this, but in this case, if we follow the steps, it will just say:

File "C:\Users\ADMIN\Downloads\botty-master\src\shop\ias_gloves.py", line 6, in <module>
    from screen import Screen
ModuleNotFoundError: No module named 'screen'

Should we explain how to load all this?

**Comment by bjoerm** [comment]
Feel free to add any steps you miss. For me it works as described above.

**Comment by karibuTW** [comment]
Okay, let me try later to load the modules and explain if any missing steps for new comers. Thanks

**Comment by karibuTW** [comment]
I guess I am missing to load the screen setup or something like this.
You have configured the init?

I'm not sure how to make it run then

Thanks

**Pull request merged**
