### PR TITLE
Enhancement: Use keyboard to select difficulty

### PR DESCRIPTION
**Pull request by roozhou**
Use key 'r', 'n', 'h' to select difficulty when starting a new game. It speeds up game creation by skipping the wait for the select difficulty UI.

### CODE REVIEW

**Comment by jagarop** [comment]
hey, i like your idea a lot. please see what you think about the small change i made.

**Comment by mgleed** [comment]
> hey, i like your idea a lot. please see what you think about the small change i made.

Notice the behavior difference between single player and online. I think send may be more appropriate unless you put back in the difficulty select box detect logic again to decide to release.

**Comment by jagarop** [comment]
https://youtu.be/7_bV0gDZYtk

**Review by mgleed — APPROVED** [review]
Thank you @roozhou and @jagarop . Added some finishing touches, deleted some unused assets. Seems to work nicely.

**Pull request merged**
