### PR TITLE
add support for custom offsets

### PR DESCRIPTION
**Pull request by mgleed**
for those struggling to get auto offset detection to work

### CODE REVIEW

**Comment by aeon0** [comment]
I dont know. If someone struggels to get auto offset work, isn't that a hint there is something wrong that will not be fixed by adding offsets?

**Comment by mgleed** [comment]
> I dont know. If someone struggels to get auto offset work, isn't that a hint there is something wrong that will not be fixed by adding offsets?

Your point is well taken, do what you will. Had a couple saying they're stuck in 0.3 because botty 0.4 won't get past the offset detect log and they showed me screenshots. In my laziness I figured this fix would be easier than having to do video chat or something for everyone with the issue.

**Comment by aeon0** [comment]
I added some debug messages about the maximum score if the templates were not found and lowered it a bit. Also added a warning if your scores are lower than usual. That should give a decent hint at what the problem might be.

I am sticking to my opinion that fixing the symptom will not fix the issue for them. You will just here follow up issues like. Stuck at eld waypoint etc.

**Comment by mgleed** [comment]
I can see where you're coming from. I don't know if I would have tried this hadn't we done something similar just this week, however. Would you agree with this same reasoning for #206 ? Either there's inconsistency with template matching (maybe platform based?) or the users aren't setting their configurations right, but either way a symptom was addressed at the cost of a feature.

**Pull request closed without merging**
