### PR TITLE
Lowered Eldritch End node

### PR DESCRIPTION
**Pull request by D2RLegit**
Need verification doesnt impact hdin or light sorc.

### CODE REVIEW

**Comment by D2RLegit** [comment]
Should be good to go now. No conflict with hdin or light sorc.

**Comment by mgleed** [comment]
What's this for? @D2RLegit

**Comment by D2RLegit** [comment]
With latest eld change blizz sorc teleports to far north of where eld is dead and will miss some drops during pickit. This fixed that issue.

**Review by mgleed — APPROVED** [review]
Thank you

**Pull request merged**
