### PR TITLE
Fix Issue #789: Select online tab before creating game when d2r switch to offline tab automatically

### PR DESCRIPTION
**Pull request by roozhou**
Added option `online_char` to params.ini.
Will check online tab status before creating games when `online_char` is 1.

### CODE REVIEW

**Comment by mgleed** [comment]
> Added option `online_char` to params.ini.
> Will check online tab status before creating games when `online_char` is 1.

This is semi implemented with game_recovery.py

On botty start it saves online status and saves template of the character so if game crashes it'll reselect the correct character. Sounds like this function could be extended for this purpose.

**Comment by roozhou** [comment]
> > Added option `online_char` to params.ini.
> > Will check online tab status before creating games when `online_char` is 1.
> 
> This is semi implemented with game_recovery.py
> 
> On botty start it saves online status and saves template of the character so if game crashes it'll reselect the correct character. Sounds like this function could be extended for this purpose.

This change reuses `select_online_tab` in character_select.py, which is also used by game_recovery.py. Something different on this issue:
1) Game does not crash.
2) It may switch back to offline even after you click the online tab. The first try always fails when it happens to me. Checking the active tab is always needed before clicking the play button.

**Comment by mgleed** [comment]
> > > Added option `online_char` to params.ini.
> > > Will check online tab status before creating games when `online_char` is 1.
> > 
> > This is semi implemented with game_recovery.py
> > 
> > On botty start it saves online status and saves template of the character so if game crashes it'll reselect the correct character. Sounds like this function could be extended for this purpose.
> 
> This change reuses `select_online_tab` in character_select.py, which is also used by game_recovery.py. Something different on this issue:
> 1) Game does not crash.
> 2) It may switch back to offline even after you click the online tab. The first try always fails when it happens to me. Checking the active tab is always needed before clicking the play button.

Agree this logic needs fixing. But if we detect the online / offline status on startup why do we need a param for it?

**Comment by roozhou** [comment]
> game_recovery.py

I don't think game_recovery.py checks online/offline status. Currently checking online status is performed in [on_select_character](https://github.com/aeon0/botty/blob/master/src/bot.py#L224) in bot.py only when `restart_d2r_when_stuck` is enabled.

Botty can also be started inside the game. What if BN disconnects after the first game?

Using `restart_d2r_when_stuck` to control online/offline status is also confusing.

**Comment by mgleed** [comment]
> > game_recovery.py
> 
> I don't think game_recovery.py checks online/offline status. Currently checking online status is performed in [on_select_character](https://github.com/aeon0/botty/blob/master/src/bot.py#L224) in bot.py only when `restart_d2r_when_stuck` is enabled.
> 
> Botty can also be started inside the game. What if BN disconnects after the first game?
> 
> Using `restart_d2r_when_stuck` to control online/offline status is also confusing.

Agree it's confusing. And you're right, it's not checked there, it's just checked on startup. 

Would this solve everything?
```
    def on_select_character(self):
-        if Config().general['restart_d2r_when_stuck']:
            # Make sure the correct char is selected
            if character_select.has_char_template_saved():
                character_select.select_char()
            else:
                character_select.save_char_online_status()
                character_select.save_char_template()
        self.trigger_or_stop("create_game")
```

**Comment by roozhou** [comment]
> Would this 1-liner solve everything?
No. This assumes your online/offline tab status is correct on your first game creation. This is not guaranteed since you are allowed to start botty inside the game.

Imagine you start botty in a game. The server lags and brings you to offline chars after exit. Botty sticks to offline thereafter.

**Review by mgleed — APPROVED** [review]
Thank you for this PR. I tested it with crashes in a few ways and found errors with game recovery that I tried to fix in this PR. I took out the online param because the only reason it would ever be necessary is if the game crashed on the very first run AND botty was launched in town. Botty appropriately detects online status for you in every other scenario.

**Comment by mgleed** [comment]
Fixes #789

**Comment by DongGamHe** [comment]
[0.7.3-dev 2022-06-08 15:55:35,564] INFO       Character select failed. Shut down botty
Exception in thread Thread-7 (start):
Traceback (most recent call last):
  File "threading.py", line 1009, in _bootstrap_inner
  File "threading.py", line 946, in run
  File "bot.py", line 163, in start
  File "bot.py", line 183, in trigger_or_stop
  File "transitions\core.py", line 899, in _get_trigger
  File "transitions\core.py", line 401, in trigger
  File "transitions\core.py", line 1201, in _process
  File "transitions\core.py", line 426, in _trigger
  File "transitions\core.py", line 435, in _process
  File "transitions\core.py", line 272, in execute
  File "transitions\core.py", line 1123, in callbacks
  File "transitions\core.py", line 1144, in callback
  File "bot.py", line 226, in on_init
  File "bot.py", line 192, in restart_or_exit
  File "utils\restart.py", line 21, in safe_exit
  File "utils\restart.py", line 25, in kill_game
  File "utils\restart.py", line 14, in process_exists
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 2: invalid start byte


I have a utf8 character and I get this error when I run the botty after the update today.

**Pull request merged**
