### PR TITLE
Added 46 uniqe / set items to pickit

### PR DESCRIPTION
**Pull request by mischavandenburg**
Added some unique and set items to the pickit.

All items have been tested with the Graphic Debugger.

### CODE REVIEW

**Comment by D2RLegit** [comment]
Everything looks fine to me other than adding 46 useless items to cram up more of the pickit.

**Review by mgleed — CHANGES_REQUESTED** [review]
Thanks @mischavandenburg . Will you set all the added items to =0 in the pickit config for the default? Otherwise looks good.

**Comment by mischavandenburg** [comment]
> Thanks @mischavandenburg . Will you set all the added items to =0 in the pickit config for the default? Otherwise looks good.

Thanks, @mgleed ! I committed and pushed again, all items should be set to 0 now.

**Review by mgleed — APPROVED** [review]

**Comment by mischavandenburg** [comment]
Great, this was my first pull request ever, and my first ever contribution to open source! Thank you for reviewing and merging, @mgleed

**Pull request merged**
